# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b046d682a6920008a50b48abf2b30a9a842d49c8ff6993cf9b095606a5d19edf66d3e56fa954d46ad9334d07b5e3b7e56b45baa44d9eea8faf3967dd4a2180ee

test:
  secret_key_base: 9bfa0cd48f6cc3fb8bc738a1cfc43f1753a26b6fd432801824c6da8a3ba17c001639d086dc0d769ae86be33b5aa4b2b5512443034c3deb43085d84db4d09bb5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
